# Generated by Django 5.1.1 on 2024-09-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cotent',
            new_name='content',
        ),
    ]
